---
  - name: ensure selinux is permissive
    selinux:
      policy: targeted
      state: permissive
    become: true  
  - name: ensure apache is installed
    package:
      name: httpd
      state: latest
    become: true  
  - name: ensure apache is started
    service:
      name: httpd
      state: started
    become: true   
  - name: ensure apache is modified 
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
       
    notify:
     - Restart Apache
   

...

      
   



      
